name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Mock run
        run: |
          python scripts/run_benchmark.py --provider mock
          python scripts/eval_metrics.py --provider mock
          python scripts/plot_results.py
          python scripts/compute_hashes.py > SHA256SUMS.txt
          python scripts/generate_sbom.py > sbom.cyclonedx.json
          python scripts/export_c2pa.py > provenance_c2pa.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mock-artifacts
          path: |
            results/mock/**
            SHA256SUMS.txt
            sbom.cyclonedx.json
            provenance_c2pa.json
